// INTERFACE PAGE. game init funcitions at bottom
// type #debug and reload for debugging menu
var debug=debug||(window.location.hash=='#debug'?1:0);
var first = ((!localStorage.player)||(localStorage.player==pla&&localStorage.scp==sc)?1:0); // set 'first' flag if the player's position is undefined or the starting coordinates
var pla=_pla.x+','+_pla.y;
var sc=_sc.x+','+_sc.y;
var a=0;
var pause=false;
var moveTime=0;
window.onload = function(e){ 
	//Touch controls
	if ("ontouchstart" in document.documentElement)
		{
			document.getElementById('cursor').style.display = 'block';
		}
	a=1;
	stats=document.getElementById('extraInfo');
	document.getElementById('TclearTime').value=_clearTime;
	timer();
	loadTracks();
	if(first){
		swap(1);
		pause=true;
		modal();
		document.getElementById('timer').innerHTML=pad(localStorage.timer,4);
		//localStorage.audio=1;//disable so audio doen't start on 'new game'
		//fix this so it persists
	}
	//audio muting persistance
	isSound=localStorage.audio;
	if(localStorage.audio!='false'){
		playSong();
	}else{
		document.getElementById('switch3').checked=false;
		localStorage.audio=false;
	}
	if (localStorage.notes == 'undefined' || localStorage.notes == null){
		document.getElementById('notes').value=_defaultText;
	}else{
		document.getElementById('notes').value=localStorage.notes;
	}
	updateStats();
}
function noteChange(){
	var dClass=(document.getElementById('notes').className=='rightnote'?'blank':'rightnote');
	document.getElementById('notes').className=dClass;
	document.getElementById('audioHolder').className=dClass;
}
function pauseGame(click){//set click to 1 if generated by a script
 	var fn = function(){ document.write('aa'); };
	if(pause){
		document.getElementById("everything").className='';
		document.getElementById('dimmer').style.display = 'none';
		document.getElementById('paused').style.display = 'none';
		document.getElementById('dimmer').style.zindex = '0';	
		document.onclick=0;
		pause=false;
	}else{
		var clicks=(click?click:0);
		document.getElementById("everything").className='blur';
		document.getElementById('dimmer').style.display = 'block';
		document.getElementById('paused').style.display = 'block';
		document.getElementById('dimmer').style.zindex = '10';	
		document.body.addEventListener('touchstart', function(event) {
			if(pause==true){
				pauseGame()
			}else{
				return;
			}
		});
		document.onclick=function(){//exit on click
			clicks++;
			if(clicks>1)
				pauseGame()
		};
		pause=true;
	}
}
function pad(time,to){
	var padl=to-time.length;
	var newstring='';
	var time2=time;
	for(var i=0;i<to;i++){
		newstring=(i<padl?newstring+'0':newstring+time.charAt(i-padl))
	}
	return newstring;
}
function timer(){
	localStorage.timer=localStorage.timer||0;
	setInterval(function(){
		if(!pause){
			localStorage.timer++;
			moveTime++;
			if(moveTime==_tillMove){
				scp.tryMove();
				moveTime=0;
			}
			document.getElementById('timer').innerHTML=pad(localStorage.timer,_padLength);
		}
	},1000);//every second
}
function sound(){
	isSound=!isSound;
	localStorage.audio=isSound;
	if(isSound){
		playSong();
	}else{
		stopSong();
	}
}
function flash(){
	var subj=document.getElementById('flash');
	subj.style.display = 'block';
	var timer=0;
	var fade=setInterval(function(){
			subj.style.display = 'none';
			clearInterval(fade);
	},100);
}
function rollover(text,clear){
	window.clearInterval(cls);
	var count=0;
	var subj=document.getElementById('tooltip');
	if(text==''){
		var count=0;
		var cls=setInterval(function(){
			count++;
			if(count==_clearTime){
				subj.className='act';
				window.clearInterval(cls);
				count=0;
			}
		},1000);
		return;
	}
	subj.innerHTML=text;
	subj.className='';
	if(clear!=0){
		var count=0;
		var cls=setInterval(function(){
			count++;
			if(count==clear){
				subj.className='act';
				window.clearInterval(cls);
				count=0;
			}
		},100);
	}

}
var fsText='Go full screen';
function fullScreen(){
	if (fsText=='Go full screen'){
		fsText='Exit full screen';
		document.getElementById('fs').src='img/small.png';
		document.getElementById('switch2').checked=true;
	}else{
		document.getElementById('switch2').checked=false
		document.getElementById('fs').src='img/full.png';
		fsText='Go full screen';
	}
	var
	el = document.documentElement
		, is = document.mozFullScreen 
	|| document.webkitIsFullScreen
		, rfs =
	el.requestFullScreen
		|| el.webkitRequestFullScreen
			|| el.mozRequestFullScreen
		, cfs = 
	document.exitFullscreen
		|| document.mozCancelFullScreen
			|| document.webkitCancelFullScreen;
			if(is)  cfs.call(document);
			else    rfs.call(el);
}
function updateStats(){
	if(!a) return;
	var stat={
		scp:{
			x:scp.x,
			y:scp.y
		},
		me:{
			x:me.x,
			y:me.y,
		}
	};
	stats.innerHTML="SCP: ["+stat.scp.x+", "+stat.scp.y+"]<br>Player: ["+stat.me.x+", "+stat.me.y+"]";
}
function saveText(){ // save the notes
	rollover('Text saved',20);
	localStorage.notes=document.getElementById('notes').value;
}
function dim() { //calls a big semi-transparent box to dim the screen
	var e = document.getElementById('dimmer');
	if(e.style.display !== 'none'){
		e.style.display = 'none';
		e.style.zIndex = '0';
	}else{

		e.style.display = 'block';
		e.style.zIndex = '10';
	}
}
var fade;
function isModal(){
	if(document.getElementById("modal").style.top=='10%')
		return true;
	return false;
}
function modal(){
	var e = document.getElementById('dimmer');
	if(isModal()){	
		pause=false;
		e.style.display = 'none';
		e.style.zIndex = '0';
		document.getElementById("everything").className=0;
		document.getElementById("modal").style.top='-400px';	
		document.getElementById('dimmer').style.display = 'none';
	}else{
		pause=true;
		e.style.zIndex = '10';
		e.style.display = 'block';
		document.getElementById("everything").className='blur';
		document.getElementById("modal").style.top='10%';	
		document.getElementById('dimmer').style.display = 'block';
	}
}
function newGame(auto){//start a new game. auto flag determines conformation box
	if(!auto){
		var check=confirm("Really start a new Game?");
		if(!check){
			return;
		}
	}
	var nn=localStorage.notes; 
	var vn=localStorage.audio; 
	localStorage.clear();
	localStorage.notes=nn; //persistant notes
	localStorage.audio=vn; //persistant sound
	location.reload();
}

var titles=['About','Settings','Help'];
function swap(n){
	document.getElementById('modal_1').style.display = (n==1?'block':'none');
	document.getElementById('modal_2').style.display = (n==2?'block':'none');
	document.getElementById('modal_3').style.display = (n==3?'block':'none');
	document.getElementById('title').innerHTML=titles[n-1];

}
function _update(){ // draw the scene
	updateStats();
	sheetengine.calc.calculateAllSheets();
	sheetengine.drawing.drawScene(true);
}
//changes a square colour both physically and in localStorage
function changeSquare(square,colour){
	if(!floor[square.x]||!matrix[square.x])
		return;
	if(!floor[square.x][square.y]||!matrix[square.x][square.y])
		return;
	floor[square.x][square.y]=colour;
	saveFloor();
	matrix[square.x][square.y].color=colours[colour];
	_update();
}
//key handlers
document.onkeydown = checkKey;
document.onkeyup = ent;
// movement keys
function checkKey(e) {
	if(document.getElementById('notes')==document.activeElement){//don't work if in textbox
		return true;
	}
	e = e || window.event;
	if (e.keyCode == _ml) {//left
		me.tryMove(0);
	}else if (e.keyCode == _mu) {// up arrow
		me.tryMove(1);
	}
	else if (e.keyCode == _mr) {//right
		me.tryMove(2);
	}
	else if (e.keyCode == _md) {// down arrow
		me.tryMove(3);
	}
	else if (e.keyCode == _pg) {// p
		pauseGame();
	}
	else if (e.keyCode == _se) {// ;
		swap(2);modal();	
	}
	else if (e.keyCode == _he) {// ?
		swap(3);modal();	
	}
	else if (e.keyCode == _fu) {// f
		document.getElementById("switch2").checked = !document.getElementById("switch2").checked; 
		fullScreen();
	}
	else if (e.keyCode == _me) {// m
		document.getElementById("switch3").checked = !document.getElementById("switch3").checked; 
		sound();
	}else{
		return true;
	}
	return false;
}
//Close open modal with esc or enter
function ent(event) {
	if ((event.which == 13 || event.keyCode == 13)||(event.keyCode == 27 || event.which == 27)) {
		if(isModal()){
			modal();
		}else{
			return true;
		}
		return false;
	}
	return true;
};
//------------------ Game ------------------
var holes=[];
var cubes=[];
function getFloor(){ 
	if(localStorage.floor){ // if it exists, parse the JSON colours from localstorage and run drawfloor()
		holes=JSON.parse(localStorage.holes);
		cubes=JSON.parse(localStorage.cubes);
		fl2=JSON.parse(localStorage.floor);
		for (var d=0;d<Object.keys(fl2).length;d++){
			floor[d]=fl2[d];
		}
		drawFloor();

	}else{ // if the string doesn't exist, make one up then run drawfloor() (also, save it for next time)
		var subj;
		var nHoles=Math.floor((Math.random()*_maxHoles)+_minHoles)
		for (var n=0;n<nHoles;n++){
				var x=Math.floor((Math.random()*13)+1);
				var y=Math.floor((Math.random()*13)+1);
				holes[n]={x:x,y:y};
		}
		var nCubes=Math.floor((Math.random()*_maxCubes)+_minCubes)
		for (var n=0;n<nCubes;n++){
				var x=Math.floor((Math.random()*13)+1);
				var y=Math.floor((Math.random()*13)+1);
				var col=Math.floor((Math.random()*4)+0);
				var rot=Math.floor((Math.random()*_cubeRotation)+0);
				cubes[n]={x:x,y:y,col:col,rot:rot};
		}
		for (var x=0; x<=14; x++) {
			floor[x]=[];     
			for (var y=0; y<=14; y++) {
				var colour=Math.floor((Math.random()*4)+0);
				floor[x][y]=colour;
			}
		}
		saveFloor();
		drawFloor();
	}
}
var dCub=[];
//save the colours of the floor in a JSON string
function saveFloor(){
	localStorage.holes=JSON.stringify(holes);
	localStorage.cubes=JSON.stringify(cubes);
	var fl=[];
	for(var d=0;d<floor.length;d++){
		fl[d]=floor[d];
	}
	localStorage.floor=JSON.stringify(fl);
}
function drawFloor(){
	//save the size of the floor for doing the side bits
	var end={x:floor.length-1,y:floor[0].length-1};
	//arrays for the side bits
	var sideX=[];
	var sideY=[];
	var holeSideX;
	var holeSideY;
	//var hole=[{x:4,y:4},{x:2,y:2}];
	var hole=holes;
	for(var x=0; x<floor.length;x++){
		things[x]=[];
		var subj=floor[x];
		matrix[x]=[];
		for(var y=0; y<subj.length;y++){
			tHole=false;
			for(var i=0;i<hole.length;i++){
				if(hole[i].x==x&&hole[i].y==y){
					var tHole=true; 
				}
			}
			if(tHole){
				//make a hole
				things[x][y]='hole';//obstruction on square
				var hole1= new sheetengine.BaseSheet({x:offset-22+x*45,y:offset+y*45,z:-20}, {alphaD:90,betaD:0,gammaD:90}, {w:40,h:45});
				var hole2= new sheetengine.BaseSheet({x:offset+x*45,y:offset-22+y*45,z:-20}, {alphaD:0,betaD:90,gammaD:0}, {w:40,h:45});
					hole1.color = colours4[floor[x-1][y]];
					hole2.color = colours3[floor[x][y-1]];
			}else{
				things[x][y]=0;
				matrix[x][y]=basesheet = new sheetengine.BaseSheet({x:offset+x*45,y:offset+y*45,z:0}, {alphaD:90,betaD:0,gammaD:0}, {w:45,h:45});
				matrix[x][y].color = colours[subj[y]];
				matrix[x][y].dim = {x:x,y:y};
				if(x==end.x){
					sideX[y]= new sheetengine.BaseSheet({x:offset-8+(x+1)*45,y:offset+15+y*45,z:0}, {alphaD:90,betaD:0,gammaD:90}, {w:20,h:45});
					sideX[y].color = colours2[subj[y]];
				}
				if(y==end.y){
					sideY[x]= new sheetengine.BaseSheet({x:offset+14+(x)*45,y:offset-8+(y+1)*45,z:0}, {alphaD:0,betaD:90,gammaD:0}, {w:20,h:45});

					sideY[x].color = colours3[subj[y]];
				}
			}
		}
	}
	//add cubes
	for(var c=0;c<cubes.length;c++){
		dCub[c]=new cube({x:cubes[c].x,y:cubes[c].y},parseInt(cubes[c].rot,10)-(_cubeRotation/2),cubes[c].col);
		
	}
}
